# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ba10640ac62afe3201162ff87d6829fa49bca15a23ad3cd49a30c4b339e3f934b0b592976f985beaddf1188fe537ddf668d5c4a21e1157e5dd0ca12244883f

test:
  secret_key_base: 895d1359b53aefc80da4d105e40c3516109428091715ee53dda8a987a0ee8a64e5c734fc9c296fe098a5c3c8b644c593e9b726b614bdd88f453036e5dffe7cd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
